version: '3'

services:
  difffify:
    build:
      context: ./difffify/
    ports:
      - "0.0.0.0:80:80"

  differ:
    build:
      context: ./differ/
    volumes:
      - ../django:/app/repo
    environment:
      - DJANGO_DEBUG=1
