version: '3'

services:
  difffify:
    build: 
      context: ./difffify/
    ports:
      - "0.0.0.0:80:80"

  differ:
    build: 
      context: ./differ/
    #ports:
    #  - "27017:27017"
    environment:
      - DJANGO_DEBUG=1
