# Generated by Django 2.0.5 on 2018-05-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1000)),
                ('additional_info_json', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='filepath',
            name='tags',
            field=models.ManyToManyField(blank=True, to='filepath.Tag'),
        ),
    ]
